# The default at [1] is 10.9 and abseil does not compile with that
# [1]: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml
MACOSX_DEPLOYMENT_TARGET:
  - 10.13  # [osx and x86_64]
